services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    container_name: asset-insight
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - variables.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - variables.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
