services:
  backend:
    image: spring-backend:AssetInsight
    container_name: backend
    build:
      context: ./BackEnd/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./BackEnd/variables.env
    depends_on:
      - db
    volumes:
      - ./BackEnd/:/backend  # Monta o código local como volume
    networks:
      - app-network
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./BackEnd/variables.env
    networks:
      - app-network
    restart: always

  angular:
    image: angular-frontend:AssetInsight
    container_name: frontend
    build:
      context: ./FrontEnd/
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
